# Generated by Django 6.0.6 on 2026-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdata',
            name='datasheet_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='componentdata',
            name='lifecycle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='componentdata',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
